<?php

/**
 * This configuration cache file was generated by Laminas\ConfigAggregator\ConfigAggregator
 * at 2024-07-07T06:30:14+00:00
 */
return [
    'dependencies' => [
        'invokables' => [
            'Psr\\Http\\Message\\RequestFactoryInterface' => 'Laminas\\Diactoros\\RequestFactory',
            'Psr\\Http\\Message\\ResponseFactoryInterface' => 'Laminas\\Diactoros\\ResponseFactory',
            'Psr\\Http\\Message\\StreamFactoryInterface' => 'Laminas\\Diactoros\\StreamFactory',
            'Psr\\Http\\Message\\ServerRequestFactoryInterface' => 'Laminas\\Diactoros\\ServerRequestFactory',
            'Psr\\Http\\Message\\UploadedFileFactoryInterface' => 'Laminas\\Diactoros\\UploadedFileFactory',
            'Psr\\Http\\Message\\UriFactoryInterface' => 'Laminas\\Diactoros\\UriFactory'
        ],
        'aliases' => [
            'Debug' => 'Webinertia\\Utils\\Debug',
            'Context' => 'App\\ContextInterface',
            'context' => 'App\\ContextInterface',
            'App\\ContextInterface' => 'App\\ContextContainer',
            'EventManager' => 'Laminas\\EventManager\\EventManagerInterface',
            'Laminas\\EventManager\\EventManagerInterface' => 'Laminas\\EventManager\\EventManager',
            'Router\\RouterInterface' => 'Router\\RouteStack',
            'User\\UserInterface' => 'User\\Entity\\User',
            'TemplateResolver' => 'Template\\TemplateResolverInterface',
            'Template\\TemplateRendererInterface' => 'Template\\TemplateRenderer'
        ],
        'factories' => [
            'Webinertia\\Utils\\Debug' => 'Laminas\\ServiceManager\\Factory\\InvokableFactory',
            'Webinertia\\Utils\\Diagnostics\\Timer' => 'Webinertia\\Utils\\Diagnostics\\TimerFactory',
            'App\\Actions\\ActionManager' => 'App\\Actions\\Container\\ActionManagerFactory',
            'App\\App' => 'App\\Container\\AppFactory',
            'App\\ContextContainer' => 'App\\Container\\ContextContainerFactory',
            'Laminas\\EventManager\\EventManager' => 'App\\Container\\EventManagerFactory',
            'App\\Listeners\\DispatchListener' => 'App\\Container\\DispatchListenerFactory',
            'App\\Listeners\\EmitResponseListener' => 'App\\Container\\EmitResponseListenerFactory',
            'App\\Listeners\\NotFoundListener' => 'App\\Container\\NotFoundListenerFactory',
            'App\\Listeners\\RenderListener' => 'App\\Container\\RenderListenerFactory',
            'App\\Listeners\\RouteListener' => 'App\\Container\\RouteListenerFactory',
            'Laminas\\HttpHandlerRunner\\Emitter\\EmitterInterface' => 'Http\\Container\\EmitterFactory',
            'Psr\\Http\\Message\\ResponseInterface' => 'Http\\Container\\ResponseFactory',
            'Psr\\Http\\Message\\ServerRequestInterface' => 'Http\\Container\\ServerRequestFactory',
            'Router\\RouteStack' => 'Router\\Container\\RouteStackFactory',
            'User\\Entity\\User' => 'User\\Entity\\Container\\UserFactory',
            'Laminas\\View\\HelperPluginManager' => 'Template\\Container\\HelperPluginManagerFactory',
            'Template\\TemplateRenderer' => 'Template\\Container\\TemplateRendererFactory',
            'Template\\TemplateResolverInterface' => 'Template\\Container\\TemplateResolverFactory',
            'Laminas\\View\\Strategy\\PhpRendererStrategy' => 'Template\\Container\\PhpRendererStrategyFactory',
            'Template\\NamespacedPathStackResolver' => 'Template\\Container\\NamespacedPathStackResolverFactory',
            'Mod\\LoginMod\\Entity\\LoginThingy' => 'Laminas\\ServiceManager\\Factory\\InvokableFactory',
            'Mod\\LoginMod\\Listener' => 'Mod\\LoginMod\\ListenerFactory'
        ],
        'delegators' => [
            'App\\App' => [
                'Http\\Container\\Psr7AwareDelegatorFactory'
            ]
        ],
        'initializers' => [
            'Template\\Container\\TemplateAwareInitializer'
        ]
    ],
    'laminas-diactoros' => [
        'x-forwarded-request-filter' => [
            'trusted-proxies' => '',
            'trusted-headers' => []
        ]
    ],
    'config_cache_path' => 'data/cache/config-cache.php',
    'action_manager' => [
        'factories' => [
            'App\\Actions\\BoardIndexAction' => 'Laminas\\ServiceManager\\Factory\\InvokableFactory',
            'App\\Actions\\DisplayAction' => 'Laminas\\ServiceManager\\Factory\\InvokableFactory',
            'App\\Actions\\MessageIndexAction' => 'Laminas\\ServiceManager\\Factory\\InvokableFactory',
            'App\\Actions\\LoginAction' => 'App\\Actions\\Container\\LoginActionFactory',
            'Mod\\LoginMod\\Actions\\CustomAction' => 'Laminas\\ServiceManager\\Factory\\InvokableFactory'
        ],
        'initializers' => [
            'App\\Actions\\Container\\EventManagerAwareInitializer',
            'Template\\Container\\TemplateAwareInitializer'
        ]
    ],
    'listeners' => [
        'Mod\\LoginMod\\Listener'
    ],
    'templates' => [
        'paths' => [
            'app' => [
                'C:\\htdocs\\event-prototype\\src\\App\\src/../templates/app',
                'C:\\htdocs\\event-prototype\\src\\Template\\src/../templates/app'
            ],
            'error' => [
                'C:\\htdocs\\event-prototype\\src\\App\\src/../templates/error'
            ],
            'layout' => [
                'C:\\htdocs\\event-prototype\\src\\App\\src/../templates/layout',
                'C:\\htdocs\\event-prototype\\src\\Template\\src/../templates/layout'
            ],
            'login-mod' => [
                'C:\\htdocs\\event-prototype\\src\\Mod\\src\\LoginMod/../templates/login-mod'
            ]
        ],
        'extension' => 'phtml',
        'layout' => 'layout:layout'
    ],
    'routes' => [
        [
            'name' => 'app.board.index',
            'query' => [],
            'methods' => [
                'GET'
            ],
            'action_class' => 'App\\Actions\\BoardIndexAction'
        ],
        [
            'name' => 'app.message.index',
            'methods' => [
                'GET'
            ],
            'query' => [
                'board'
            ],
            'action_class' => 'App\\Actions\\MessageIndexAction'
        ],
        [
            'name' => 'app.display',
            'methods' => [
                'GET',
                'POST'
            ],
            'query' => [
                'topic'
            ],
            'action_class' => 'App\\Actions\\DisplayAction'
        ],
        [
            'name' => 'app.login',
            'query' => [
                'action' => 'login'
            ],
            'methods' => [
                'GET',
                'POST'
            ],
            'action_class' => 'App\\Actions\\LoginAction'
        ],
        [
            'name' => 'app.login.loginTwo',
            'query' => [
                'action' => 'login',
                'sa' => 'loginTwo'
            ],
            'methods' => [
                'GET',
                'POST'
            ],
            'action_class' => 'App\\Actions\\LoginAction'
        ],
        [
            'name' => 'loginmod.custom.action',
            'query' => [
                'action' => 'custom-action'
            ],
            'methods' => [
                'GET'
            ],
            'action_class' => 'Mod\\LoginMod\\Actions\\CustomAction'
        ]
    ],
    'template_helpers' => [],
    'template_helper_config' => [
        'doctype' => 'HTML5'
    ],
    'App\\ActionInterface' => [],
    'actions' => [],
    'debug' => false,
    'config_cache_enabled' => true,
    'mock-data' => [
        'User\\UserInterface' => [
            'userId' => 0,
            'userName' => 'Guest',
            'role' => 'guest'
        ]
    ]
];

